import 'package:get_storage/get_storage.dart';

String Loginphone = "";
String Signupname = "";
String Signupphone = "";
String Signupemail = "";
List<Map<String, dynamic>> CartItems = [];
int TotalCost = 0;
int FinalTotalCost = 0;
int GrandTotalCost = 0;
int GrandTotalCostWithDelivery = 0;
String UserID = '';
int lengthOfCart = 0;
List<Map<String, dynamic>> AddressBook = [];
String PickupDate = '';
String DeliveryDate = '';
String PickupTime = '';
String DeliveryTime = '';
String ExtraNotes = '';
String SupportRider = '';
const String apiKey = "AIzaSyAlcZM-RHySJIQmUwOaJmJCVPZcuMKS70Y";
String paymentMode = '';
String ALatitude = '';
String ALongitude = '';
String PlaceID = '';
